// Code generated by go-swagger; DO NOT EDIT.

// Package http order-api
//
//	API specification for the order-api service
//	Schemes:
//	  https
//	Host: 127.0.0.1
//	BasePath: /api/v1/order
//	Version: 1.0.1
//
//	Consumes:
//	  - application/json
//
//	Produces:
//	  - application/json
//
// swagger:meta
package http
