// Code generated by go-swagger; DO NOT EDIT.

package order

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/krivenkov/order/internal/server/http/models"
)

// CreateOrderOKCode is the HTTP code returned for type CreateOrderOK
const CreateOrderOKCode int = 200

/*
CreateOrderOK OK

swagger:response createOrderOK
*/
type CreateOrderOK struct {

	/*
	  In: Body
	*/
	Payload *models.CreateOrderResponse `json:"body,omitempty"`
}

// NewCreateOrderOK creates CreateOrderOK with default headers values
func NewCreateOrderOK() *CreateOrderOK {

	return &CreateOrderOK{}
}

// WithPayload adds the payload to the create order o k response
func (o *CreateOrderOK) WithPayload(payload *models.CreateOrderResponse) *CreateOrderOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create order o k response
func (o *CreateOrderOK) SetPayload(payload *models.CreateOrderResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateOrderOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CreateOrderBadRequestCode is the HTTP code returned for type CreateOrderBadRequest
const CreateOrderBadRequestCode int = 400

/*
CreateOrderBadRequest Bad Request

swagger:response createOrderBadRequest
*/
type CreateOrderBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewCreateOrderBadRequest creates CreateOrderBadRequest with default headers values
func NewCreateOrderBadRequest() *CreateOrderBadRequest {

	return &CreateOrderBadRequest{}
}

// WithPayload adds the payload to the create order bad request response
func (o *CreateOrderBadRequest) WithPayload(payload *models.Error) *CreateOrderBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create order bad request response
func (o *CreateOrderBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateOrderBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CreateOrderUnauthorizedCode is the HTTP code returned for type CreateOrderUnauthorized
const CreateOrderUnauthorizedCode int = 401

/*
CreateOrderUnauthorized Unauthorized

swagger:response createOrderUnauthorized
*/
type CreateOrderUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewCreateOrderUnauthorized creates CreateOrderUnauthorized with default headers values
func NewCreateOrderUnauthorized() *CreateOrderUnauthorized {

	return &CreateOrderUnauthorized{}
}

// WithPayload adds the payload to the create order unauthorized response
func (o *CreateOrderUnauthorized) WithPayload(payload *models.Error) *CreateOrderUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create order unauthorized response
func (o *CreateOrderUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateOrderUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CreateOrderInternalServerErrorCode is the HTTP code returned for type CreateOrderInternalServerError
const CreateOrderInternalServerErrorCode int = 500

/*
CreateOrderInternalServerError Internal Server Error

swagger:response createOrderInternalServerError
*/
type CreateOrderInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewCreateOrderInternalServerError creates CreateOrderInternalServerError with default headers values
func NewCreateOrderInternalServerError() *CreateOrderInternalServerError {

	return &CreateOrderInternalServerError{}
}

// WithPayload adds the payload to the create order internal server error response
func (o *CreateOrderInternalServerError) WithPayload(payload *models.Error) *CreateOrderInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create order internal server error response
func (o *CreateOrderInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateOrderInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
