// Code generated by go-swagger; DO NOT EDIT.

package order

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/krivenkov/order/internal/server/http/models"
)

// DeleteOrderNoContentCode is the HTTP code returned for type DeleteOrderNoContent
const DeleteOrderNoContentCode int = 204

/*
DeleteOrderNoContent OK

swagger:response deleteOrderNoContent
*/
type DeleteOrderNoContent struct {
}

// NewDeleteOrderNoContent creates DeleteOrderNoContent with default headers values
func NewDeleteOrderNoContent() *DeleteOrderNoContent {

	return &DeleteOrderNoContent{}
}

// WriteResponse to the client
func (o *DeleteOrderNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

// DeleteOrderUnauthorizedCode is the HTTP code returned for type DeleteOrderUnauthorized
const DeleteOrderUnauthorizedCode int = 401

/*
DeleteOrderUnauthorized Unauthorized

swagger:response deleteOrderUnauthorized
*/
type DeleteOrderUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteOrderUnauthorized creates DeleteOrderUnauthorized with default headers values
func NewDeleteOrderUnauthorized() *DeleteOrderUnauthorized {

	return &DeleteOrderUnauthorized{}
}

// WithPayload adds the payload to the delete order unauthorized response
func (o *DeleteOrderUnauthorized) WithPayload(payload *models.Error) *DeleteOrderUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete order unauthorized response
func (o *DeleteOrderUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteOrderUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteOrderForbiddenCode is the HTTP code returned for type DeleteOrderForbidden
const DeleteOrderForbiddenCode int = 403

/*
DeleteOrderForbidden Forbidden

swagger:response deleteOrderForbidden
*/
type DeleteOrderForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteOrderForbidden creates DeleteOrderForbidden with default headers values
func NewDeleteOrderForbidden() *DeleteOrderForbidden {

	return &DeleteOrderForbidden{}
}

// WithPayload adds the payload to the delete order forbidden response
func (o *DeleteOrderForbidden) WithPayload(payload *models.Error) *DeleteOrderForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete order forbidden response
func (o *DeleteOrderForbidden) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteOrderForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteOrderNotFoundCode is the HTTP code returned for type DeleteOrderNotFound
const DeleteOrderNotFoundCode int = 404

/*
DeleteOrderNotFound Not Found

swagger:response deleteOrderNotFound
*/
type DeleteOrderNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteOrderNotFound creates DeleteOrderNotFound with default headers values
func NewDeleteOrderNotFound() *DeleteOrderNotFound {

	return &DeleteOrderNotFound{}
}

// WithPayload adds the payload to the delete order not found response
func (o *DeleteOrderNotFound) WithPayload(payload *models.Error) *DeleteOrderNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete order not found response
func (o *DeleteOrderNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteOrderNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteOrderInternalServerErrorCode is the HTTP code returned for type DeleteOrderInternalServerError
const DeleteOrderInternalServerErrorCode int = 500

/*
DeleteOrderInternalServerError Internal Server Error

swagger:response deleteOrderInternalServerError
*/
type DeleteOrderInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteOrderInternalServerError creates DeleteOrderInternalServerError with default headers values
func NewDeleteOrderInternalServerError() *DeleteOrderInternalServerError {

	return &DeleteOrderInternalServerError{}
}

// WithPayload adds the payload to the delete order internal server error response
func (o *DeleteOrderInternalServerError) WithPayload(payload *models.Error) *DeleteOrderInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete order internal server error response
func (o *DeleteOrderInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteOrderInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
