// Code generated by go-swagger; DO NOT EDIT.

package order

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/krivenkov/order/internal/server/http/models"
)

// GetOrdersCountOKCode is the HTTP code returned for type GetOrdersCountOK
const GetOrdersCountOKCode int = 200

/*
GetOrdersCountOK OK

swagger:response getOrdersCountOK
*/
type GetOrdersCountOK struct {

	/*
	  In: Body
	*/
	Payload *models.GetCountResponse `json:"body,omitempty"`
}

// NewGetOrdersCountOK creates GetOrdersCountOK with default headers values
func NewGetOrdersCountOK() *GetOrdersCountOK {

	return &GetOrdersCountOK{}
}

// WithPayload adds the payload to the get orders count o k response
func (o *GetOrdersCountOK) WithPayload(payload *models.GetCountResponse) *GetOrdersCountOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get orders count o k response
func (o *GetOrdersCountOK) SetPayload(payload *models.GetCountResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetOrdersCountOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetOrdersCountUnauthorizedCode is the HTTP code returned for type GetOrdersCountUnauthorized
const GetOrdersCountUnauthorizedCode int = 401

/*
GetOrdersCountUnauthorized Unauthorized

swagger:response getOrdersCountUnauthorized
*/
type GetOrdersCountUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetOrdersCountUnauthorized creates GetOrdersCountUnauthorized with default headers values
func NewGetOrdersCountUnauthorized() *GetOrdersCountUnauthorized {

	return &GetOrdersCountUnauthorized{}
}

// WithPayload adds the payload to the get orders count unauthorized response
func (o *GetOrdersCountUnauthorized) WithPayload(payload *models.Error) *GetOrdersCountUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get orders count unauthorized response
func (o *GetOrdersCountUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetOrdersCountUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetOrdersCountInternalServerErrorCode is the HTTP code returned for type GetOrdersCountInternalServerError
const GetOrdersCountInternalServerErrorCode int = 500

/*
GetOrdersCountInternalServerError Internal Server Error

swagger:response getOrdersCountInternalServerError
*/
type GetOrdersCountInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetOrdersCountInternalServerError creates GetOrdersCountInternalServerError with default headers values
func NewGetOrdersCountInternalServerError() *GetOrdersCountInternalServerError {

	return &GetOrdersCountInternalServerError{}
}

// WithPayload adds the payload to the get orders count internal server error response
func (o *GetOrdersCountInternalServerError) WithPayload(payload *models.Error) *GetOrdersCountInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get orders count internal server error response
func (o *GetOrdersCountInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetOrdersCountInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
