// Code generated by go-swagger; DO NOT EDIT.

package order

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/krivenkov/order/internal/server/http/models"
)

// GetOrdersOKCode is the HTTP code returned for type GetOrdersOK
const GetOrdersOKCode int = 200

/*
GetOrdersOK OK

swagger:response getOrdersOK
*/
type GetOrdersOK struct {

	/*
	  In: Body
	*/
	Payload *models.GetOrdersResponse `json:"body,omitempty"`
}

// NewGetOrdersOK creates GetOrdersOK with default headers values
func NewGetOrdersOK() *GetOrdersOK {

	return &GetOrdersOK{}
}

// WithPayload adds the payload to the get orders o k response
func (o *GetOrdersOK) WithPayload(payload *models.GetOrdersResponse) *GetOrdersOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get orders o k response
func (o *GetOrdersOK) SetPayload(payload *models.GetOrdersResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetOrdersOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetOrdersBadRequestCode is the HTTP code returned for type GetOrdersBadRequest
const GetOrdersBadRequestCode int = 400

/*
GetOrdersBadRequest Bad Request

swagger:response getOrdersBadRequest
*/
type GetOrdersBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetOrdersBadRequest creates GetOrdersBadRequest with default headers values
func NewGetOrdersBadRequest() *GetOrdersBadRequest {

	return &GetOrdersBadRequest{}
}

// WithPayload adds the payload to the get orders bad request response
func (o *GetOrdersBadRequest) WithPayload(payload *models.Error) *GetOrdersBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get orders bad request response
func (o *GetOrdersBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetOrdersBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetOrdersUnauthorizedCode is the HTTP code returned for type GetOrdersUnauthorized
const GetOrdersUnauthorizedCode int = 401

/*
GetOrdersUnauthorized Unauthorized

swagger:response getOrdersUnauthorized
*/
type GetOrdersUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetOrdersUnauthorized creates GetOrdersUnauthorized with default headers values
func NewGetOrdersUnauthorized() *GetOrdersUnauthorized {

	return &GetOrdersUnauthorized{}
}

// WithPayload adds the payload to the get orders unauthorized response
func (o *GetOrdersUnauthorized) WithPayload(payload *models.Error) *GetOrdersUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get orders unauthorized response
func (o *GetOrdersUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetOrdersUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetOrdersInternalServerErrorCode is the HTTP code returned for type GetOrdersInternalServerError
const GetOrdersInternalServerErrorCode int = 500

/*
GetOrdersInternalServerError Internal Server Error

swagger:response getOrdersInternalServerError
*/
type GetOrdersInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetOrdersInternalServerError creates GetOrdersInternalServerError with default headers values
func NewGetOrdersInternalServerError() *GetOrdersInternalServerError {

	return &GetOrdersInternalServerError{}
}

// WithPayload adds the payload to the get orders internal server error response
func (o *GetOrdersInternalServerError) WithPayload(payload *models.Error) *GetOrdersInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get orders internal server error response
func (o *GetOrdersInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetOrdersInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
