// Code generated by go-swagger; DO NOT EDIT.

package order

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetOrdersHandlerFunc turns a function with the right signature into a get orders handler
type GetOrdersHandlerFunc func(GetOrdersParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn GetOrdersHandlerFunc) Handle(params GetOrdersParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// GetOrdersHandler interface for that can handle valid get orders params
type GetOrdersHandler interface {
	Handle(GetOrdersParams, interface{}) middleware.Responder
}

// NewGetOrders creates a new http.Handler for the get orders operation
func NewGetOrders(ctx *middleware.Context, handler GetOrdersHandler) *GetOrders {
	return &GetOrders{Context: ctx, Handler: handler}
}

/*
	GetOrders swagger:route GET / order getOrders

Get a list of all orders
*/
type GetOrders struct {
	Context *middleware.Context
	Handler GetOrdersHandler
}

func (o *GetOrders) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetOrdersParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
