// Code generated by go-swagger; DO NOT EDIT.

package order

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetOrdersCountHandlerFunc turns a function with the right signature into a get orders count handler
type GetOrdersCountHandlerFunc func(GetOrdersCountParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn GetOrdersCountHandlerFunc) Handle(params GetOrdersCountParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// GetOrdersCountHandler interface for that can handle valid get orders count params
type GetOrdersCountHandler interface {
	Handle(GetOrdersCountParams, interface{}) middleware.Responder
}

// NewGetOrdersCount creates a new http.Handler for the get orders count operation
func NewGetOrdersCount(ctx *middleware.Context, handler GetOrdersCountHandler) *GetOrdersCount {
	return &GetOrdersCount{Context: ctx, Handler: handler}
}

/*
	GetOrdersCount swagger:route GET /orders/count order getOrdersCount

Get a count of all orders
*/
type GetOrdersCount struct {
	Context *middleware.Context
	Handler GetOrdersCountHandler
}

func (o *GetOrdersCount) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetOrdersCountParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
