// Code generated by go-swagger; DO NOT EDIT.

package order

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/krivenkov/order/internal/server/http/models"
)

// UpdateOrderOKCode is the HTTP code returned for type UpdateOrderOK
const UpdateOrderOKCode int = 200

/*
UpdateOrderOK OK

swagger:response updateOrderOK
*/
type UpdateOrderOK struct {

	/*
	  In: Body
	*/
	Payload *models.UpdateOrderResponse `json:"body,omitempty"`
}

// NewUpdateOrderOK creates UpdateOrderOK with default headers values
func NewUpdateOrderOK() *UpdateOrderOK {

	return &UpdateOrderOK{}
}

// WithPayload adds the payload to the update order o k response
func (o *UpdateOrderOK) WithPayload(payload *models.UpdateOrderResponse) *UpdateOrderOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update order o k response
func (o *UpdateOrderOK) SetPayload(payload *models.UpdateOrderResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateOrderOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// UpdateOrderBadRequestCode is the HTTP code returned for type UpdateOrderBadRequest
const UpdateOrderBadRequestCode int = 400

/*
UpdateOrderBadRequest Bad Request

swagger:response updateOrderBadRequest
*/
type UpdateOrderBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewUpdateOrderBadRequest creates UpdateOrderBadRequest with default headers values
func NewUpdateOrderBadRequest() *UpdateOrderBadRequest {

	return &UpdateOrderBadRequest{}
}

// WithPayload adds the payload to the update order bad request response
func (o *UpdateOrderBadRequest) WithPayload(payload *models.Error) *UpdateOrderBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update order bad request response
func (o *UpdateOrderBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateOrderBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// UpdateOrderUnauthorizedCode is the HTTP code returned for type UpdateOrderUnauthorized
const UpdateOrderUnauthorizedCode int = 401

/*
UpdateOrderUnauthorized Unauthorized

swagger:response updateOrderUnauthorized
*/
type UpdateOrderUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewUpdateOrderUnauthorized creates UpdateOrderUnauthorized with default headers values
func NewUpdateOrderUnauthorized() *UpdateOrderUnauthorized {

	return &UpdateOrderUnauthorized{}
}

// WithPayload adds the payload to the update order unauthorized response
func (o *UpdateOrderUnauthorized) WithPayload(payload *models.Error) *UpdateOrderUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update order unauthorized response
func (o *UpdateOrderUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateOrderUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// UpdateOrderForbiddenCode is the HTTP code returned for type UpdateOrderForbidden
const UpdateOrderForbiddenCode int = 403

/*
UpdateOrderForbidden Forbidden

swagger:response updateOrderForbidden
*/
type UpdateOrderForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewUpdateOrderForbidden creates UpdateOrderForbidden with default headers values
func NewUpdateOrderForbidden() *UpdateOrderForbidden {

	return &UpdateOrderForbidden{}
}

// WithPayload adds the payload to the update order forbidden response
func (o *UpdateOrderForbidden) WithPayload(payload *models.Error) *UpdateOrderForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update order forbidden response
func (o *UpdateOrderForbidden) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateOrderForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// UpdateOrderNotFoundCode is the HTTP code returned for type UpdateOrderNotFound
const UpdateOrderNotFoundCode int = 404

/*
UpdateOrderNotFound Not Found

swagger:response updateOrderNotFound
*/
type UpdateOrderNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewUpdateOrderNotFound creates UpdateOrderNotFound with default headers values
func NewUpdateOrderNotFound() *UpdateOrderNotFound {

	return &UpdateOrderNotFound{}
}

// WithPayload adds the payload to the update order not found response
func (o *UpdateOrderNotFound) WithPayload(payload *models.Error) *UpdateOrderNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update order not found response
func (o *UpdateOrderNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateOrderNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// UpdateOrderInternalServerErrorCode is the HTTP code returned for type UpdateOrderInternalServerError
const UpdateOrderInternalServerErrorCode int = 500

/*
UpdateOrderInternalServerError Internal Server Error

swagger:response updateOrderInternalServerError
*/
type UpdateOrderInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewUpdateOrderInternalServerError creates UpdateOrderInternalServerError with default headers values
func NewUpdateOrderInternalServerError() *UpdateOrderInternalServerError {

	return &UpdateOrderInternalServerError{}
}

// WithPayload adds the payload to the update order internal server error response
func (o *UpdateOrderInternalServerError) WithPayload(payload *models.Error) *UpdateOrderInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update order internal server error response
func (o *UpdateOrderInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateOrderInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
